---
# Debian/Ubuntu specific variables
foomuuri_service_name: "foomuuri"
foomuuri_config_path: "/etc/foomuuri"
foomuuri_binary_path: "/usr/sbin/foomuuri"

# Debian/Ubuntu package names
foomuuri_debian_dependencies:
  - python3
  - python3-requests
  - python3-dbus
  - python3-gi
  - python3-systemd
  - nftables
