---
- name: Ensure default user is present.
  community.mysql.mysql_user:
    name: "{{ mariadb_user_name }}"
    host: 'localhost'
    password: "{{ mariadb_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  when: mariadb_user_name != mariadb_root_username

# Has to be after the password assignment, for idempotency.
- name: Copy user-my.cnf file with password credentials.
  ansible.builtin.template:
    src: "user-my.cnf.j2"
    dest: "{{ mariadb_user_home }}/.my.cnf"
    owner: "{{ mariadb_user_name }}"
    mode: '0600'
  when: >
    mariadb_user_name != mariadb_root_username
    and (mariadb_install_packages | bool or mariadb_user_password_update)

- name: Disallow root login remotely
  ansible.builtin.command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mariadb_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the root user.
  ansible.builtin.command: mysql -NBe
    "SELECT Host
    FROM mysql.user
    WHERE User = '{{ mariadb_root_username }}'
    ORDER BY (Host='localhost') ASC"
  register: mariadb_root_hosts
  changed_when: false
  check_mode: false
  # Expliciete definitie van mislukking:
  failed_when: mariadb_root_hosts.rc != 0 or mariadb_root_hosts.stderr | length > 0
  when: mariadb_install_packages | bool or mariadb_root_password_update

# Note: We do not use community.mysql.mariadb_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x).
  ansible.builtin.shell: >
    mysql -u root -NBe
    'ALTER USER "{{ mariadb_root_username }}"@"{{ item }}"
    IDENTIFIED WITH mariadb_native_password BY "{{ mariadb_root_password }}"; FLUSH PRIVILEGES;'
  with_items: "{{ mariadb_root_hosts.stdout_lines | default([]) }}"
  changed_when: update_root_password.rc == 0
  when: >
    ((mariadb_install_packages | bool) or mariadb_root_password_update)
    and ('5.7.' in mariadb_cli_version.stdout or '8.0.' in mariadb_cli_version.stdout)

# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  ansible.builtin.shell: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mariadb_root_username }}"@"{{ item }}" = PASSWORD("{{ mariadb_root_password }}"); FLUSH PRIVILEGES;'
  with_items: "{{ mariadb_root_hosts.stdout_lines | default([]) }}"
  changed_when: update_root_password_legacy.rc == 0
  when: >
    ((mariadb_install_packages | bool) or mariadb_root_password_update)
    and ('5.7.' not in mariadb_cli_version.stdout and '8.0.' not in mariadb_cli_version.stdout)

# Has to be after the root password assignment, for idempotency.
- name: Copy .my.cnf file with root password credentials.
  ansible.builtin.template:
    src: "root-my.cnf.j2"
    dest: "{{ mariadb_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: '0600'
  when: mariadb_install_packages | bool or mariadb_root_password_update

- name: Get list of hosts for the anonymous user.
  ansible.builtin.command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mariadb_anonymous_hosts
  changed_when: false
  check_mode: false

- name: Remove anonymous MySQL users.
  community.mysql.mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mariadb_anonymous_hosts.stdout_lines | default([]) }}"

- name: Remove MySQL test database.
  community.mysql.mysql_db:
    name: 'test'
    state: absent
