---
- name: Ensure MySQL users are present.
  community.mysql.mysql_user:
    login_user: "{{ mariadb_root_username | default('root') }}"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mariadb_users }}"
  no_log: true
