---
- name: Ensure replication user exists on master.
  community.mysql.mysql_user:
    name: "{{ mariadb_replication_user.name }}"
    host: "{{ mariadb_replication_user.host | default('%') }}"
    password: "{{ mariadb_replication_user.password }}"
    priv: "{{ mariadb_replication_user.priv | default('*.*:REPLICATION slave,REPLICATION CLIENT') }}"
    state: present
  when:
    - mariadb_replication_role == 'master'
    - mariadb_replication_user.name is defined
    - (mariadb_replication_master | length) > 0

- name: Check mariadb_slave replication status.
  community.mysql.mysql_replication:
    mode: getslave
    login_user: "{{ mariadb_replication_user.name }}"
    login_password: "{{ mariadb_replication_user.password }}"
  ignore_errors: true
  register: mariadb_slave
  when:
    - mariadb_replication_role == 'mariadb_slave'
    - (mariadb_replication_master | length) > 0

- name: Check master replication status.
  community.mysql.mysql_replication:
    mode: getmaster
    delegate_to: "{{ mariadb_replication_master if mariadb_replication_master | length > 0 else 'SomeFakeStringBecauseOtherwisePlaybookBreaks' }}"
  register: mariadb_master
  when:
    - >
      (
        (mariadb_slave.Is_mariadb_slave is defined and not mariadb_slave.Is_mariadb_slave)
        or
        (mariadb_slave.Is_mariadb_slave is not defined and mariadb_slave is failed)
      )
    - mariadb_replication_role == 'mariadb_slave'
    - (mariadb_replication_master | length) > 0

- name: Configure replication on the mariadb_slave.
  community.mysql.mysql_replication:
    mode: changemaster
    master_host: "{{ mariadb_replication_master }}"
    master_user: "{{ mariadb_replication_user.name }}"
    master_password: "{{ mariadb_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  failed_when: false
  when:
    - >
      (
        (mariadb_slave.Is_mariadb_slave is defined and not mariadb_slave.Is_mariadb_slave)
        or
        (mariadb_slave.Is_mariadb_slave is not defined and mariadb_slave is failed)
      )
    - >
      (
        (mariadb_slave.Is_mariadb_slave is defined and not mariadb_slave.Is_mariadb_slave)
        or
        (mariadb_slave.Is_mariadb_slave is not defined and mariadb_slave is failed)
      )
    - mariadb_replication_role == 'mariadb_slave'
    - mariadb_replication_user.name is defined
    - (mariadb_replication_master | length) > 0

- name: Start replication.
  community.mysql.mysql_replication:
    mode: startmariadb_slave
  when:
    - >
      (
        (mariadb_slave.Is_mariadb_slave is defined and not mariadb_slave.Is_mariadb_slave)
        or
        (mariadb_slave.Is_mariadb_slave is not defined and mariadb_slave is failed)
      )
    - mariadb_replication_role == 'mariadb_slave'
    - (mariadb_replication_master | length) > 0
