---
galaxy_info:
  author: tubby1981
  description: Role for installing, configuring, and managing phpMyAdmin with customizable URL path
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - phpmyadmin
    - mysql
    - mariadb
    - database
    - webserver
    - security

dependencies:
  - role: php
    php_install_enabled: true
