---
# AlmaLinux 9 / Rocky Linux 9 / RHEL 9
__mariadb_daemon: mariadb
__mariadb_packages:
  - mariadb-server
  - mariadb
  - mariadb-connector-c
  - python3-PyMySQL
  - mariadb-backup
__mariadb_slow_query_log_file: /var/log/mysql-slow.log
__mariadb_log_error: /var/log/mariadb/mariadb.log
__mariadb_syslog_tag: mariadb
__mariadb_pid_file: /var/run/mariadb/mariadb.pid
__mariadb_config_file: /etc/my.cnf.d/mariadb-server.cnf
__mariadb_config_include_dir: /etc/my.cnf.d
__mariadb_socket: /var/lib/mysql/mysql.sock
__mariadb_supports_innodb_large_prefix: false
