---
# Debian 13 (Trixie)
__mariadb_daemon: mariadb
__mariadb_packages:
  - default-mysql-server
  - default-mysql-client
  - python3-mysqldb
  - mariadb-backup
  - python3-pymysql
mariadb_log_file_group: adm
__mariadb_slow_query_log_file: /var/log/mysql/mariadb-slow.log
__mariadb_log_error: /var/log/mysql/error.log
__mariadb_syslog_tag: mysqld
__mariadb_pid_file: /run/mysqld/mysqld.pid
__mariadb_config_file: /etc/mysql/my.cnf
__mariadb_config_include_dir: /etc/mysql/mariadb.conf.d
__mariadb_socket: /run/mysqld/mysqld.sock
__mariadb_supports_innodb_large_prefix: false
