---
# handlers file for php

- name: Restart PHP-FPM
  ansible.builtin.service:
    name: "{{ php_fpm_service_name }}"
    state: restarted
  become: true

- name: Reload PHP-FPM
  ansible.builtin.service:
    name: "{{ php_fpm_service_name }}"
    state: reloaded
  become: true

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
  when: php_webserver_name == "apache2"

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
  when: php_webserver_name == "nginx"
